name: Cache

on:
  schedule:
    - cron: "37 * * * *"


jobs:
  cache_regions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Read .nvmrc
        run: echo "nvm=$(cat .nvmrc)" >> "$GITHUB_OUTPUT"
        id: nvm

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - name: Fetch regions
        run: yarn workspace @las-motillos/acciona-client cache-regions

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update acciona-client/assets/regions.json
          branch: master
          file_pattern: acciona-client/assets/regions.json

